In [1]:
import preprocessing
from util import DatabaseAdapter
import analysis


da = DatabaseAdapter.Database(r'E:\Users\Sebastian\PycharmProjects\amazon-spam-detection\data')
df = da.retrieve_dataframe('CellPhonesAndAccessories', 10000, 'asin, reviewTime, class, overall')
#preprocessing.preprocess(df)
analysis.analyse(df)

E:\Users\Sebastian\PycharmProjects\amazon-spam-detection\bin\util\DatabaseAdapter.py:230: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  dataframe = pd.read_sql_query(

                       occurrences  overall
asin       reviewtime
B00DVH62J2 2013-12-29           34     4.72
           2014-03-09           28     4.84
B00DVHZ0Q8 2014-04-20            5     4.12
B00DVIHGAK 2014-01-12           10     4.00
           2014-02-09           10     4.00
...                            ...      ...
B00DYYIITY 2014-02-09            2     4.50
           2014-03-23            5     4.38
           2014-04-20            3     4.00
B00DYYTO4M 2014-01-26            4     4.25
           2014-04-06            5     4.75

[321 rows x 2 columns]

In [ ]:
import pandas as pd
import preprocessing


df = pd.DataFrame({'asin': ['1a', '1a', '1a', '2b', '2b', '3c'], 'reviewtime': ['2023-11-26','2023-11-22', '2024-11-16', '2022-11-23'
    , '2022-11-13', '2022-11-13'], 'overall': ['1', '1', '1', '1', '1', '1']})
df = preprocessing.preprocess(df, minimum_reviews=1)
print(df)

In [ ]:
import numpy as np
from scipy.signal import find_peaks, peak_prominences
import matplotlib.pyplot as plt

x = np.linspace(0, 6 * np.pi, 1000)
x = np.sin(x) + 0.6 * np.sin(2.6 * x)
peaks, _ = find_peaks(x, width = 100)
prominences, left_bases, right_bases = peak_prominences(x, peaks)
contour_heights = x[peaks] - prominences
plt.plot(x)
plt.plot(peaks, x[peaks], "x")
#plt.plot(left_bases, x[left_bases], "*")
#plt.plot(right_bases, x[right_bases], "*")
plt.vlines(x=peaks, ymin=contour_heights, ymax=x[peaks])
plt.show()

In [2]:
from matplotlib.pyplot import plot
import pandas as pd
import analysis

df = pd.DataFrame({'asin': ['1a', '1a', '1a', '1a', '1a', '1a', '1a', '1a', '1a', '2b', '2b', '3c'], 'reviewtime': ['2023-11-26','2023-11-22',' 2024-04-14', '2024-05-12', '2024-05-12',' 2024-05-12', '2024-04-14', '2024-04-14', '2024-11-16', '2022-11-23', '2022-11-13', '2022-11-13'], 'overall': [1,1,1,1,1,1,1,1,1,1,1,1]})
df = analysis.analyse(df, 1)
df

            occurrences
reviewtime
2024-04-14            3
2024-05-12            3
Empty DataFrame
Columns: [occurrences]
Index: []
Empty DataFrame
Columns: [occurrences]
Index: []

                 occurrences  overall
asin reviewtime
1a   2024-04-14            3      1.0
     2024-05-12            3      1.0

In [1]:
to_plot = df.loc[['1a']]['occurrences']
to_plot = to_plot.reset_index()
to_plot = to_plot.drop(columns = 'asin')
to_plot = to_plot.set_index(['reviewtime'])
plot(to_plot)

            occurrences
reviewtime
2024-04-14            3
2024-05-12            3
Empty DataFrame
Columns: [occurrences]
Index: []
Empty DataFrame
Columns: [occurrences]
Index: []

AttributeError: 'str' object has no attribute 'loc'

In [1]:
import pandas as pd
offset=3
zeros = pd.Series(0, index=range(offset))